### ISSUE TITLE
It doesn't work in a context-free manner.

### ISSUE THREAD

**Issue by stjeong** [GiovanniDicanio/StringCaseConversion#1]
As you stated,

https://giodicanio.com/2024/10/09/how-to-convert-unicode-strings-to-lower-case-and-upper-case-in-c-plus-plus/

"You cannot convert in a context-free manner like that wchar_t-by-wchar_t, as context involving adjacent wchar_ts can indeed be important for the conversion."

then, LCMapStringEx is expected to be able to convert it, but it is not.

For example, 

    {
        wstring s1 = L"TEST\xd803\xdc80";  // U+10C80 
        wstring s2 = ToStringLower(s1); // expected: U+10CC0

        Check(s2 == L"test\xd803\xdcc0"); // assert always!
    }

It has to be passed, but it failed.

**Comment by GiovanniDicanio** [comment]
I'm not sure, but there might be an issue/bug with the LCMapStringEx API;
see for example this question on StackOverflow:

https://stackoverflow.com/q/79142316/1629821

**Comment by stjeong** [comment]
I see... :) Anyway, thanks for your try. 

I also read the article "A popular but wrong way to convert a string to uppercase or lowercase" from "oldnewthing", and write some code using LCMapStringEx with various flags for parameters, which was not work. Then, I searched... led me to this repo.

With your work, I knew not working is normal... :)
