### ISSUE TITLE
C2397 | conversion from 'DWORD' to 'int' requires a narrowing conversion

### ISSUE THREAD

**Issue by TonyMuniz** [GiovanniDicanio/StringCaseConversion#2]
I'm trying to build this solution in VS 2022 x64 (17.11.6) but receiving the error:

![vc2022_C2397](https://github.com/user-attachments/assets/cf97aacf-fcec-4ab4-a7c4-6653a0d2d35c)

I've confirmed Warning Level set to '/W4' and C++ Language Standard set to 'ISO C++ 17 Standard'

Any suggestions on project and/or code changes to get a successful build?

**Comment by GiovanniDicanio** [comment]
In lines 96 and 100 try replacing `errorCode` with:

`static_cast<int>(errorCode)`



Il giorno mar 3 dic 2024 alle 14:34 Tony Muniz ***@***.***>
ha scritto:

**Comment by TonyMuniz** [comment]
Thanks - that worked.

And thanks for posting this solution; I don't do a lot of C++ programming, and it was helpful to find ToLower/ToUpper solution with more thought (and best practices) put into it than I would muster.

**Comment by GiovanniDicanio** [comment]
You’re welcome! Glad to be of help.

Il giorno mar 3 dic 2024 alle 17:20 Tony Muniz ***@***.***>
ha scritto:
